### ISSUE TITLE
Consider global_position BIGSERIAL PRIMARY KEY in messages table

### ISSUE THREAD

**Issue by mattbishop** [message-db/message-db#10]
The DDL for messages has a separate statement to add a primary key: https://github.com/message-db/message-db/blob/master/database/tables/messages.sql#L12

Wouldn't this be simpler to declare the primary key in the table creation statement? It it not the same result?

  global_position BIGSERIAL PRIMARY KEY

**Comment by sbellware** [comment]
I'm not sure of "simpler". They're equivalent syntaxes.

The table's primary key is far to important to not hook the reader's attention by having it commingled with the table definition using the PRIMARY KEY shortcut syntax.

**Comment by mattbishop** [comment]
Simpler in two ways--less text to reason about and reliant on the default behaviour of Postgres. But, as you say, they are equivalent.

**Comment by sbellware** [comment]
I'm not really sure it could be characterized as "default" behavior. It's more like convenient syntactic sugar. Under the hood, it's expanded to something more akin to the separate line. Ultimately, there's even more going on since even the sequence is a separate Postgres object, the index is a separate object, etc.

But again, usability is not about compressing the number of things to reason about. In the end, the concept count is the same. But by separating the declaration, the implementation highlights the table's primary key, which is ultimately the goal of the implementation and its choices.

The primary key is emphasized by isolating it from the table declaration. Part of the reason for this is that most users are predisposed to presume that an `id` field would be the primary key, which is not the case for an event store data model, where the ID is more akin to a commit ID than a relational row identifier. The Message DB implementation doesn't support that rather uncommon pattern as a matter of practicality and limiting the number and complexity of patterns supported (and thus encourage users to adopt much more elaborate technologies when such patterns are going to be common in their solutions).
