### ISSUE TITLE
message-db as a PostgreSQL extension 

### ISSUE THREAD

**Issue by lizmccormack** [message-db/message-db#12]
I am working with a write-heavy database and wanted to know if message-db can be used as a PostgreSQL extension or only as its own database instance?

**Comment by sbellware** [comment]
Hi @lizmccormack.

Message DB is available as SQL scripts that define the message store database.

It's not packaged as a PostgreSQL extension due to the limitations that cloud providers place on the installation of extensions.

It can totally be installed into an existing Postgres database. And, of course, it can be installed into its own database.

The default installation is intended for people who may not be entirely familiar with Postgres operations and administration. By default, the scripts create a new database named `message_store`.

But it's all just SQL scripts. You can download the code from GitHub and make any changes you need to specialize it for your purposes.

Here's the line in the `install.sh` script that creates the database: https://github.com/message-db/message-db/blob/master/database/install.sh#L69

If you comment out that line of code, it won't create a new database. You can further adapt the code to install the message_store objects into an existing database.

NOTE: All of the objects in the database are also contained in a Postgres schema named `message_store`, so installing Message DB's objects into an existing database is safe and isolated.

I hope this answers your question. Please feel free to continue clarifying in case I've misunderstood your essential point.
