### ISSUE TITLE
Allow installation / upgrade using plain SQL

### ISSUE THREAD

**Issue by aflatter** [message-db/message-db#14]
Hello,

I'm toying around with `message-db` and I'm wondering why shell scripts are used for installation and updates. I'd love to use `message-db` with my existing migration utilities, but to do that I'd have to pull all of the SQL together manually with each new version of `message-db`. Curious about your thoughts!

Thanks

**Comment by sbellware** [comment]
Hi, @aflatter. Sorry for the late response. I had not noticed that your issue was filed until just now.

Message DB is entirely framework-agnostic and language agnostic. We can't possibly maintain scripts for every particular ORM tool in every particular language.

The right answer for the Message DB project is to provide the most universal, native, and general purpose form of code that serves all particular, specialized use cases. The most universal, native, and general purpose choice for a PostgreSQL product running on a Unix is PL/pgSQL and Bash.

The rest of this answer presumes that you're using Rails. I'm basing that assumption on your GitHub profile and the use of the word "migration" in relation to database schema management. I'm assuming that you're referring to ActiveRecord migrations.

It's worth pointing out that while Message DB can be added to an existing Rails app database, it's not entirely a natural thing to do for Message DB.

Message DB isn't a Rails plug-in. It's an entirely stand-alone database product that just so happens to coincidentally be built on Postgres. Putting the Message DB schema inside your Rails app database would be like installing any third-party database schema directly into your own first-party database schema. The Message DB database isn't just some tables and indexes that you can leverage via ActiveRecord, or other such ORM tool.

Putting the Message DB schema inside your Rails app database would be like installing SugarCRM's database schema or Mastodon's database schema right into your Rails app's database schema.

There are far better ways that don't have the same long-term cost implications to achieve that kind of integration. And _it is_ an _integration_, not a plug-in, like Devise or something similar that generates ActiveRecord migrations.

When a schema is specifically intended to be a plug-in or add-on to a Rails application, then that plug-in will provide migration scripts. When a schema is an entirely stand-alone product, migration scripts wouldn't be provided, and shouldn't be provided.

That said, under certain conditions, you might indeed want to install Message DB into a Rails app database. For example, if you wanted to write to Rails application data _and_ write to Message DB in the same atomic database transaction. But you might have to do a good deal of hacking of ActiveRecord's connection pool internals to make that happen. At the moment, such a thing isn't even supported in Message DB's Ruby client (but it may be in the future).

In the end, Message DB doesn't have to be managed using your Rails application's database schema management tools. Message DB isn't _of_ Rails. It's not a Rails thing. It's a Message DB thing. It would be a bit of a cognitive glitch or quirk to see Message DB and a Rails app database as the same thing only because they're both Postgres databases. Your Rails app data and the Message DB data may be _adjacent to each other_, but they're not _of each other_. Integrating these two things doesn't mean making them the same, it means leaving them as they are and integrating them.

Ultimately, you can execute Message DB's native schema management scripts (or the Bundler executables that ship with the Message DB RubyGem) from a Rails migration script, but it's arguable whether there would be any significant advantage in doing that. All it does is change where the Message DB installation code is called from. The Message DB installation code still needs to be called no matter what.

And if you're customizing Message DB - changing it from its inherent and native form so that it can coexist in some other database rather than Message DB's own native database - then that's inevitably customization. In such a case, you own that code and that specialization. And that's ultimately why Message DB's schema definition code is provided in the most universal form possible; so that users can specialize the database for any number of the infinite operational configurations that users might need or want for their particular language, framework, or operations topology.

In the end, we provide the baseline code. Users bring their own particularities and special needs to the table. We provide the code in the most universal form possible, which enables users to do whatever kinds of particular specializations they need.

I hope this helps clarify things.

If you want to chat more about your use case and what you want to figure out, please reach out on the Eventide Project's Slack on the #usage channel: https://eventide-project-slack.herokuapp.com. There are a few folks there who are using Message DB from within Rails, and I know they'd be happy to share what they've learned.

**Comment by aflatter** [comment]
@sbellware Hi Scott, thank you so much for that elaborate comment. I'll try to give a little bit more context: I'm currently not working with Rails, although that does not matter too much for my question. I'm building a little prototype backend using Postgraphile (and [postgraphile-migrate](https://github.com/graphile/migrate)). With that stack, my business logic already lives in a Postgres. For one part of the application, I woud love to use an event-sourced data model and I was thinking about using Message DB to avoid having to re-implement event streams myself.

So yeah, the idea was to put Message DB into the same database (maybe in a different schema) and add a couple of functions on top to create events and to derive projections from streams. I do understand now, that you're looking at message-db more like a separate database server that can be added to an application stack.

It seems that my question regarding a plain SQL version of the Message DB distribution stems from a different understanding of this project's scope. For me, it would be amazing if I could just put Message DB side by side with the rest of my database, because it's much simpler to maintain - plus I can now create abstractions on top of it using postgres functions. Sounds like a very attractive solution to me.

Is this just something you had no need for yet? Do you see any technical problems preventing this? If that's not the vision of this project, that's totally fine of course.

I currently do not spend a lot of time on that prototype, but I'm happy to join Slack and discuss things if that helps. Just let me know.

**Comment by sbellware** [comment]
@aflatter It would be great to talk about this in the Slack if only to expose more people to the different things that people are doing with Message DB. 

Message DB is already in its own Postgres schema named `message_store`. So, that should give you namespace isolation from any existing database you want to install it into.

You can override the target database name as well as deactivate the creation of a specific database for Message DB. Both of those options used together should address your scenario for installing into an existing database.

You can find examples of both options in the docs at: http://docs.eventide-project.org/user-guide/message-db/install.html#database-name

One of the Message DB users, @josephchoe, I believe installs Message DB into an existing database. He's on the Slack as well. You might be able to get some input from him on is setup.

I hope this helps!

**Comment by noahseger** [comment]
@aflatter I have been looking at exactly the same thing with postgraphile, so I'm interested if you get it working!

**Comment by sbellware** [comment]
@aflatter @noahseger If you guys want to do a video conference and talk through it a bit more, we'd be happy to accommodate. Ultimately, accelerating our arrival at an understanding of both your workflows and of PostGraphile is going to bring us all closer to be able to make some decisions.

**Comment by aflatter** [comment]
> @aflatter I have been looking at exactly the same thing with postgraphile, so I'm interested if you get it working!

Wow, that's amazing to hear! I haven't found the time to work on this, but had the idea to generate a plain SQL version by rebinding the "psql" command to simply write its input to disk and then executing the Message DB install script.

> @aflatter @noahseger If you guys want to do a video conference and talk through it a bit more, we'd be happy to accommodate. Ultimately, accelerating our arrival at an understanding of both your workflows and of PostGraphile is going to bring us all closer to be able to make some decisions.

Sure, why not, let's do this! It would be great to lower the barrier to sprinkle a bit of event-sourcing into existing apps.

**Comment by sbellware** [comment]
@aflatter @noahseger I'm available this Friday (May 15) at pretty much any time. I'm in the Central Time zone, so I suspect some time in my morning would be good for you given the time offset with Hamburg? I have another call scheduled from 10am to 11am my time, but the rest of the morning is open. Let me know and I'll put something in my schedule.

**Comment by aflatter** [comment]
@sbellware I'm going to join the Eventide Slack to make things a bit easier. @noahseger Feel free to join too :)
