### ISSUE TITLE
Issue Running get_stream_messages

### ISSUE THREAD

**Issue by hussaino** [message-db/message-db#18]
When I try to run the sample get_stream_messages from the installation instructruction in your README page I get the following error:

Query 1 ERROR: ERROR:  Retrieval with SQL condition is not activated
CONTEXT:  PL/pgSQL function get_stream_messages(character varying,bigint,bigint,character varying) line 34 at RAISE

Query:
SELECT * FROM get_stream_messages('someStream-123', 0, 1000, condition => 'messages.time >= current_time');

Clearly the condition parameter at the end is not required, so when I omit it, it runs without issues.
My client is TablePlus on the MacOS. I am using your library in a Docker environment using [this implementation](https://github.com/SuchSoftware/message-db-docker). I am following the book: Practical Microservices and the writer doesn't even seem to use this function.
I am planning to use this with my NestJs microservices project, so I will be writing a wrapper module to your library that I will probably share online.

Thanks in advanced.

**Comment by sbellware** [comment]
@hussaino The `condition` parameter is disabled by default as a security consideration. We don't want to deploy by default a feature that could be understood as a SQL injection vector (even if it's not a SQL injection vector). Nonetheless, in order to reassure users who may be disquieted by the capability, and who are not in a position to understand its implementation, it's protected with a feature flag.

It's enabled with a Postgres configuration setting: `message_store.sql_condition`.

Here's some more background on the feature and the setting: http://docs.eventide-project.org/user-guide/message-db/server-functions.html#filtering-messages-with-a-sql-condition

**Comment by hussaino** [comment]
Great, thank you for the quick response. I've enabled the feature flag and it works right away. 

However, I had to change a minor part of the tutorial to the following:
`SELECT * FROM get_stream_messages('someStream-123', 0, 1000, condition => 'messages.time::time >= current_time');`
* I added ::time and the end of the condition

Thank you again for your help

**Comment by sbellware** [comment]
Thanks, @hussaino. I've updated the docs to reflect the corrected casting of the time value. Much appreciated!
