### ISSUE TITLE
What was the consideration when choosing cardinal_id as the partition key for consumer groups?

### ISSUE THREAD

**Issue by nordfjord** [message-db/message-db#48]
Opening this issue as a learning opportunity for myself.

I see that the consumer_group query uses

```sql
MOD(@hash_64(cardinal_id(stream_name)), $6) = $5
```

What were the considerations that led to the cardinal_id being chosen as the partition key rather than the whole stream_name?

**Comment by sbellware** [comment]
If a stream name has an entity ID that is a compound entity ID, the secondary ID is subsidiary to the cardinal ID, suggesting that the secondary ID represents something that is part of the entity identified by the cardinal ID. It's the cardinal ID that is the de facto identifier of the entity, and the entity's stream. The use cases for a compound ID are mostly mechanical, and it's unlikely to be used for applicative purposes.

Only the cardinal ID can specifically identify an entity. The secondary ID in a compound ID doesn't identify a distinct entity. If the secondary ID did identify a distinct entity, it wouldn't be identified with a secondary ID, but a cardinal ID.

All messages for a given entity should always be handled by the same consumer node, and the cardinal ID is the only identifier that distinguishes entities from each other.

**Comment by nordfjord** [comment]
I see, thanks for the clarification, I understand your point of view.

For what it's worth, this is a different mental model from my own. In my mind a stream and an entity are the same and therefore the only true identifier is the whole `stream_name`.

Another notable difference is that I structure my stream_id from least specific to most specific. e.g. `{Category}-{TenantId}_{EntityId}`

> All messages for a given entity should always be handled by the same consumer node

Here I wholeheartedly agree, But I do disagree that the cardinal identifier represents an entity uniquely. Most likely we have different mental models of what an Entity is. As stated above, I believe a stream and an entity are the same, and therefore the only thing that can uniquely distinguish an entity is the whole of the `stream_name`

On a side note. Because I use a different separator (`_` rather than `+`) my whole `stream_id` is considered as the cardinal id by message db, meaning I ultimately do not run into any problems due to this behaviour.

**Comment by nordfjord** [comment]
In any case, thanks for taking the time to respond. Helpful as ever! I hope my perspective was at the very least of some value to you.

I'll close this issue as resolved as I've gotten the information I wanted.

**Comment by sbellware** [comment]
> As stated above, I believe a stream and an entity are the same, and therefore the only thing that can uniquely distinguish an entity is the whole of the stream_name

The stream name definitely identifies a stream uniquely, but a stream and an entity can't be seen as the same thing. The stream is just a storage model and medium for an entity.

For example, an instance of `SalesOrder` with an ID of `123` only ever has a unique identifier of `123`.  We can know this must be true because `SalesOrder.new.id = "salesOrder-123"` would ultimately be an absurdity. The category or class of an entity isn't part of its ID.  

> On a side note. Because I use a different separator (_ rather than +) my whole stream_id is considered as the cardinal id by message db, meaning I ultimately do get the behaviour I'd expect.

Indeed! And that's exactly the solution that you need. Ignore the fact that entity ID's _can_ be composed of the entity ID + a secondary, subsidiary ID. That secondary ID addresses a very specific mechanical use case which is almost exclusively the domain of tool and framework development, rather than applicative development.
