### ISSUE TITLE
Why do you choose self maintained counter with explicit lock, but not Sequence?

### ISSUE THREAD

**Issue by Hixon10** [message-db/message-db#5]
Hello!

This project seems very interesting. So I begin to read the source code.

I have one architecture question. Can you explain, why you choose self maintained counter with explicit lock, but not Sequence?

I mean, you have the following code to insert a message:
```
pg_advisory_xact_lock()
....
_next_position := _stream_version + 1;
```

So, there is a https://www.postgresql.org/docs/current/sql-createsequence.html

Is there any reason, to not use `sequence`?

**Comment by sbellware** [comment]
@Hixon10 Indeed, there's a very good reason.

The position number of a message in a stream must never have gaps or else using the `position` as an optimistic concurrency protection would not be guaranteed to work.

Postgres sequences have gaps.

For example, if a write failed, the sequence can be incremented, but there might not be a record with that sequence number.

The `global_position` attribute is a Postgres sequence. That's ultimately because it doesn't matter if `global_position` has gaps.

**Comment by Hixon10** [comment]
@sbellware hello, thank you for the response.
