### ISSUE TITLE
Support for bi-temporal messages?

### ISSUE THREAD

**Issue by stevesimmons** [message-db/message-db#6]
Hi Scott,

Firstly, great project! I've been looking for ages for the database part of a message store. I plan on building on your Postgres message store schema, reading and writing objects from Python.

One feature I would love is bi-temporal timestamps on messages. So have you considered adding direct support for messages that may have both an event_time and a entry_time? 

This is useful for scenarios like correcting old txns in a financial system, back-populating historical messages from another message store, etc.

One solution could be to add the second timestamp (event_time) to a json blob in the  message's `metadata` field. But this bi-temporal nature feels more like an intrinsic property of the messages and we would like low-level db functions to retrieve messages in either logical or entry time ordering.

**Comment by sbellware** [comment]
@stevesimmons Hi. Glad you like the product :)

The `time` attribute on the `messages` table is purely for mechanical or diagnostic purposes. It's only purpose is to record the time that an event is physically recorded in the store. It's not applicative (application) data, and really should not be used as applicative data.

All applicative data belongs belongs in the `data` attribute, which is where the message body's data is stored.

So, if you've got an event_time and an entry_time, they're inevitably applicative data rather than mechanical data about a row in the `messages` table.

It's common to see multiple timestamps in a message's applicative data. For example, `processed_time` and `effective_time`, which correlate to event_time and an entry_time. But they go in the applicative data container in a `messages` record, which is the `data` attribute.

For example, here's the definition of an account withdrawal event from an example component written in Ruby:

```
class Withdrawn
  include Messaging::Message

  attribute :account_id, String
  attribute :amount, Numeric
  attribute :time, String
  attribute :processed_time, String
end
```

The `time` attribute is the effective time and the `processed_time` attribute is the processed time.

So, yes, it's common to have more than one time attribute on a message. But it's the message's data, not the data of the mechanical record in the `messages` table. You could technically have anywhere from 0 time attributes to infinite time attributes. It depends entirely on the business domain and the business requirements, and its the responsibility of the message's data to convey the specifics of messages in the domain, rather than the database record that contains that message data.

Hope this helps!

**Comment by sbellware** [comment]
PS: Having just taken a quick glance at your GitHub profile and noting that you're doing stuff with Python data analytics and sensor data, I'm wondering if the thing on your mind is optimized access to the two time attributes that you're concerned with _without_ having to extract them from the Postgres JSON object in the `data` field.

Just in case that is what's on your mind, there are a number of ways that you can customize the `messages` table and/or the `write_message` function to make that happen. That would mean maintaining your own fork of the message store, but we tend to see the base Message DB code as a starting point, anyway. For the vast majority of users, the schema will be used stock out of the box, and for some users who need specialization, the code will inevitably be customized.

For example, you can use generated columns in Postgres 12 (https://www.postgresql.org/docs/12/ddl-generated-columns.html) to promote message data attributes to the `messages` table by adding generated column definitions to the `messages` table. Or you could override the implementation of the `write_message` function to update a customized `messages` table schema.

And any of these (and other customizations) can be done as overrides (rather than direct modifications) using Postgres schemas and the Postgres schema search path (https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH).

**Comment by stevesimmons** [comment]
> I'm wondering if the thing on your mind is optimized access to the two time attributes that you're concerned with without having to extract them from the Postgres JSON object in the data field.

Your suggestion to use generated columns is a good one.

I am looking to train models to predict future customer behaviour, from an event-sourced history for each customer. The `data` field is JSON with that event's payload. The `metadata` field, also JSON, will contain three things: relevant timestamps, associated entity ids (customer, etc), and event type/version. Selected items from `metadata` will be exposed as generated columns and indexed. 

As to my application domain:
* In the past I worked a lot on trading systems (commodities/fx) where the current state of a trading book was the logical result of applying events such as buy/sell/exercise an option/pay coupon/amend/etc on the underlying financial instruments. An amend, for instance, may have been applied today but backdated for a trade yesterday.
* Right now, I am doing consumer finance modelling, and want to build marketing and risk models that can say, for instance, "at time T1, based on everything I knew about customer X up to T1, which offer at T1 optimizes for profit contribution at T2 6 months later". This feels like I need an event store that lets me replay history of customer X up to T1, observe the state of customer X, then replay up to T2 and observe the outcome. This data lets me build models.... I have order of 100k customers and 10m events. So indexing and streaming them out of the db needs to be efficient. Once I have that, I can split by customer and process as a highly parallelised map-reduce job.

**Comment by sbellware** [comment]
Yup, this sounds like the sweet spot for an event store.

You may not need to go to the extent of using generated columns for this, though. Postgres' JSON querying and indexing capabilities are quite strong. There are some examples of this in the Message DB code itself.

Here's an index that includes an attribute of a Postgres JSON document: https://github.com/message-db/message-db/blob/master/database/indexes/messages-category.sql#L6

Here's an example of using a JSON document attribute in a WHERE clause: https://github.com/message-db/message-db/blob/master/database/functions/get-category-messages.sql#L48

You might also consider using views or materialized views with values extracted from the JSON documents using Postgres JSON expressions.

So, you've got a lot of good options at hand for your kind of application before needing to modify the `messages` table directly, but generated columns on the `messages` table remains an option. Really depends on the tradeoffs of read vs. write optimization and your particular needs and performance profile.

The data you've identified as message metadata sounds like it might just be data rather than metadata. Timestamps, entity ids, and so forth and are typically event data. The metadata is usually used for mechanical data pertinent to messaging patterns, rather than data that would be application or domain data.

The event version is definitely metadata.

Also, the `messages` table has a column for the event type, so that value wouldn't need to be in the message metadata.
