### ISSUE TITLE
Message table retention/maintenance 

### ISSUE THREAD

**Issue by gamefundas** [message-db/message-db#7]
Nice project, message-db actually fits nicely for one of my use case where we are using Kafka. 

Have a question though on the message retention and general maintenance of the message-store table. In Kafka we operate with a retention of 7 days beyond which the messages are discarded. How does this work in message-db? The message table could grow indefinitely otherwise. 

What sort of periodic maintenance is recommended if this is a manual process?

**Comment by sbellware** [comment]
@gamefundas Good stuff. Message DB is indeed targeted at the same patterns as Kafka. Of course, it's not really targeted at super-massive scale as Kafka is. And thus, it comes with a lot lower operational overhead.

There's nothing automated in Eventide that handles message erasure. But it's just Postgres. It's pretty trivial to implement a reaper per your requirements. Cleaning up expired messages is just a matter of a SQL `DELETE FROM messages WHERE {condition}`. It can be scheduled using something like `cron`, or any other task scheduler.

There's nothing automated that is provided with Eventide for three reasons:

1-) The Eventide Project itself can't be in the business of providing code that delete's users' messages. That's just too much of a liability.
2-) We couldn't solve all user scenarios no matter how abstract we made a reaper tool.
3-) Not all users want to erase any messages at all.

And ultimately, since it is just Postgres, we leave the message erasure implementation to the prerogatives of the user.

PS: If you'd like more realtime answers to your questions, consider joining the Eventide Slack: https://eventide-project-slack.herokuapp.com/
