### ISSUE TITLE
Consumer architecture

### ISSUE THREAD

**Issue by gamefundas** [message-db/message-db#8]
If I understand this correctly consumers use the position as offsets to read messages.

Does it mean they will be designed to poll at periodic intervals to pick the incoming streams?

How does this work in case of multiple consumers for the same stream, consume exactly once has to be build outside of this using some dedupe mechanics?

**Comment by ntl** [comment]
Can you clarify what you mean by consumers "[using] the position as offsets to read messages?" I'll try to do by best to answer your questions in the meantime:

Consumers read category streams (which are themselves comprised of all the individual entity streams that belong to said category) sequentially. They periodically store positions offsets so that if they are restarted, they can pick up near where they left off. This is not an idempotence mechanism; idempotence must be guaranteed by the message handlers (indeed, this is true for any message transport). When multiple consumers read the same category stream, they must not store their positions offsets in the same place. This often means assigning identifiers to consumers that read from the same category.

**Comment by sbellware** [comment]
@gamefundas Affirming what @ntl said: There's no such thing in any messaging system as _consuming_ exactly once. There's only _processing_ exactly once. The only guarantee that a message transport can offer is that consumers will receive messages more than once. It's up to the business logic running inside those consumers to determine whether an input message is being received more than once, and to either ignore or process the message.

So, message handlers (no matter which message transport or message broker or message queue is used) have to be able to receive any recycled message more than once. That's true even with message transports that support ACKs of deletes.

The ACK message is never guaranteed to be processed, resulting in messages that had been ACKed being received again because the ACK wasn't processed and the last message is still in the queue.

So, Eventide consumers store their position offset every 100 messages (this number is configurable). The handlers inside the consumers need to be prepared to process up to 100 messages that they had already processed in the past.

If two separate consumers are going to be processing the same stream, the consumer needs to specify a unique identifier to differentiate the stream names of the position offset streams.

Here's an example of a consumer that declares the identifier property:
http://docs.eventide-project.org/user-guide/consumers.html#example

And like @ntl said, this isn't an idempotence mechanism. It's only intended to speed up the start-up process of a consumer. Rather than forcing a consumer to re-process every single input message, it skips to the last recorded offset position.
